### ISSUE TITLE
Move commonly used dictionary items into the post_info_dict

### ISSUE THREAD

**Issue by cdsciavolino** [cornell-sun/sun-wordpress#11]
Right now, there's some discrepancies between the response returned by the `/featured` endpoint and the normal `/posts` endpoint. Move the commonly-used ones into the `post_info_dict` dictionary for consistency across the board.

**Comment by AAAstorga** [comment]
Keys we need:
id
date
title
title.rendered
content
content.rendered
excerpt
excerpt.rendered
link
author
