### ISSUE TITLE
Array of Content Components in Article Views

### ISSUE THREAD

**Issue by cdsciavolino** [cornell-sun/sun-wordpress#12]
Instead of returning the HTML that should be rendered on the app, we should parse the HTML and return the information necessary to render the information. Kind of create an array of some Renderable class and return that rather than the HTML. i.e. we should do something like this

``` html
<p>text content going here</p>
<img src='something.com' alt='inline photo'>
<p>More text here</p>
<iframe ... src='some video.mp3'>
<p>More text</p>
```

should instead be something like:
``` javascript
[
{
    "type": "text",
    "content": "text content going here"
},
{
    "type": "image",
    "src": "something.com"
},
...
]
```

**Comment by AAAstorga** [comment]
I understand this is a long project, but I think this is a higher priority than some other issues. I want to make sure the article page is as clean as it could be. Let me know what you think the ETA is on this and how me/others can help! :)

**Comment by steamingcow** [comment]
Logic is contained on frontend.
