### ISSUE TITLE
Fix Facebook Comments

### ISSUE THREAD

**Issue by cdsciavolino** [cornell-sun/sun-wordpress#21]
* Facebook comments are not broken due to Facebook restricting access to user information through the Graph API
	* As of right now, the `access_token` we generate does not have enough permissions to receive the `from` field in the default comment response
	* This isn’t broken on the current website because all the plugin they use does is call a Facebook URL that generates the comment box for it.
		* When fixing, the most likely outcome will be we have to do the same thing with this plugin, get an HTML document response back, and parse that into a list of comments
	* If we try and generate a page access token on the Graph API Explorer, it looks like we *still* don’t get the user information in the response

**Comment by CameronHamidi** [comment]
It was decided that Facebook comments will not be displayed in the app.

**Comment by CameronHamidi** [comment]
It was decided that Facebook comments will not be displayed in the app.
